config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = Movie.all
  end

  def show
    @list = Movie.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <h1>All lists</h1>
  <div class="row">
    <% @lists.each do |list| %>
      <div class="col-md-4">
        <%= link_to list.title, list_path(list) %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/show.html.erb
  <div class="container">
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= @list.title %></h5>
      <p class="card-text"><%= @list.overview %></p>
      <p class="card-text"><%= @list.rating %></p>
      <% if @list.poster_url.present? %>
        <%= image_tag @list.poster_url, class: "card-img-top" %>
      <% else %>
        <p>No poster available</p>
      <% end %>
    </div>
  </div>
</div>